### ISSUE TITLE
Alternative writing

### ISSUE THREAD

**Issue by Zeugma4242** [Oopdawg/summer-work#3]
https://github.com/Oopdawg/summer-work/blob/34e2efe32685ecefd567a7ea01d132df29257e3b/python/baseConverter.py#L14-L15

reverse is fine to reverse the sequence. however, as the list was just built, an alternative is to create the list out of the sequence already in the right order:

`num[::-1] ` # returns the sequence in reverse. `num = '123' `will return `'321'`

list(sequence) create a list which each element from the sequence. An str is a sequence and each element is a char.

so `list(num[::-1]) `give the same result.

To be a bit more readable, 'reversed' is a built-in function reversing the sequence order

`list(reversed('123'))`  works too

**Comment by Oopdawg** [comment]
done
