### ISSUE TITLE
Avoid copy paste of code outside of while loop

### ISSUE THREAD

**Issue by Zeugma4242** [Oopdawg/summer-work#5]
https://github.com/Oopdawg/summer-work/blob/34e2efe32685ecefd567a7ea01d132df29257e3b/python/baseConverter.py#L22-L30

With a bit of logic, no need to copy code and run it once out of the loop.
Goal is to run the loop at list once, whatever the quotient value to begin with.
This is true is the `endDigits` is empty, so we can test for that:

```
endDigits = []
quotient = numBase10

while quotient or not endDigits:
    quotient, remainder = divmod(quotient, endBase)
    endDigits.append(remainder)
```

**Comment by Zeugma4242** [comment]
And yes divmod does the 2 operations at once when we need both the quotient and the remainder, no need to call 2 operations.

**Comment by Oopdawg** [comment]
fixed
